# Generated by Django 5.1.4 on 2025-01-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggeditem',
            old_name='contenttype',
            new_name='content_type',
        ),
    ]
